### ISSUE TITLE
Ambiguous reference to member 'onSwipe'

### ISSUE THREAD

**Issue by boardmain** [igormatyushkin014/Sensitive#5]
hi , i have this error
sensitive installed via Podfile

and on the view.onswipe i see that error

(it found 2 candidates, bot from Sensitive.UIView )

**Comment by igormatyushkin014** [comment]
@boardmain Hi,

Which version of Swift are you using?

**Comment by igormatyushkin014** [comment]
@boardmain Try it with Swift 4. It should work properly. I'm closing this issue because I haven't received a response from you. Feel free to reopen the issue if the bug appears when using Swift 4.
