### ISSUE TITLE
Multiple onTap gestures fire when UIViews overlap

### ISSUE THREAD

**Issue by netgfx** [igormatyushkin014/Sensitive#6]
Is there a way to give priority/stop propagation or identify which gesture is recognized? I have some UIViews (a list) and a button that overlap and when I `tap` on the button the list also receives an event.

**Comment by igormatyushkin014** [comment]
@netgfx

**Comment by igormatyushkin014** [comment]
@netgfx Update `Sensitive` to version `7.0`:

```
pod 'Sensitive', '7.0'
```

It includes significant improvements of the syntax.

The issue you've described is fixed in the latest version.
